### PR TITLE
adds "offsets" Cell component

### PR DESCRIPTION
**Pull request by Undeadlol1**

### CODE REVIEW

**Comment by tb** [comment]
@Undeadlol1 nice feature but "eslint docs src scripts" is failing the CI

**Comment by Undeadlol1** [comment]
@tb what does it mean? What is needed to be done? Refactor according to eslint settings?

**Comment by tleunen** [comment]
Indeed, it will be best to fix these small issues:
```
./src/Grid.js
  40:30  error  Unexpected block statement surrounding arrow body  arrow-body-style
  40:30  error  Missing space after =>                             arrow-spacing
  40:66  error  Missing semicolon                                  semi
```

**Comment by Undeadlol1** [comment]
Done and done

**Comment by tleunen** [comment]
Thanks @Undeadlol1, I'll merge it tonight after adding the new props in the documentation :)

**Pull request merged**
