### PR TITLE
Added ripple effect to the checkbox component. This fixes issue #63

### PR DESCRIPTION
**Pull request by peterssonjesper**
See https://github.com/tleunen/react-mdl/issues/63

### CODE REVIEW

**Comment by faergeek** [comment]
Looks good :+1: 

Just a few hints:

1. There are eslint errors, you can them if you type `npm run lint`.
2. It's more comfortable for both sides to create branch other than `master` in your repo and then send PR.

**Comment by peterssonjesper** [comment]
Sorry, was in a bit of a hurry there! The linting errors have been fixed. Do you want me to create a new pull request from my new branch?

Thanks!

**Comment by faergeek** [comment]
I think it's no necessary for now.
It's just more comfortable for submitter and reviewer.
Just a hint for your future PRs :-)

**Comment by faergeek** [comment]
@tleunen Please take a look at this.

**Comment by tleunen** [comment]
Thanks @peterssonjesper

**Pull request merged**
