### PR TITLE
Setup testing suite

### PR DESCRIPTION
**Pull request by faergeek**
See #57 

Here are my suggested test suite with code coverage, watching and shallow rendering utils.
I used some of my expectations about `Badge` component as an example :-)
And tests fail. It deserves separate discussion probably.

So, what you can do with it:

1. You can run tests once with `npm test`
2. You can run watcher which will rerun on change with `npm run test:watch`
3. You can produce code coverage report with `npm run test:cov` and see the report by opening `coverage/lcov-report/index.html` in browser.
But the folder is empty if tests failed.
It's possible to see it by temporarily commenting the last two tests though.

What do you think about all of that?

### CODE REVIEW

**Comment by faergeek** [comment]
P.S. I still would like to use http://speckjs.github.io/ but it probably will require some custom code to easily test react render output.

**Comment by faergeek** [comment]
Need to fix test running as it silently fails now in Travis.

**Comment by tleunen** [comment]
I agree with the coverage but I have no plan to move to tape.

**Comment by faergeek** [comment]
But why? There are not much tests yet, I can covert them to tape easily.

**Pull request closed without merging**
