### PR TITLE
Support for programmatic change of Textfield value

### PR DESCRIPTION
**Pull request by faergeek**
This will correctly work with floatingLabel when
change from empty value or to empty value

### CODE REVIEW

**Comment by tleunen** [comment]
What's the usecase?
Would have thought that because the value has changed, the textfield is re-rendered and therefore MDL should check the validity.

**Comment by faergeek** [comment]
Try to update value using react-devtools from empty to some value and backwards. If value assigned programmatically, then label will be under real text and vice versa.

**Comment by faergeek** [comment]
I have a real use case where I'm editing images and when I switch them some images have filled values and some don't.

**Comment by faergeek** [comment]
Not sure if it's needed for validation, though.

**Comment by tleunen** [comment]
Good catch.
Actually, this is because the MDL object is already initialized.
We might want to use `.change()` on the MDL object if we detect the value has changed.

**Comment by faergeek** [comment]
I tried using `.change()`, seems like it doesn't work that way. Did you test it?

**Comment by tleunen** [comment]
Not yet no... But it should work since it updates the css.

**Comment by faergeek** [comment]
Usually such methods assume that you know what you're doing and handled everything, so it does not dispatch event.

**Comment by faergeek** [comment]
Ping

**Comment by faergeek** [comment]
@tleunen So what about that PR?

**Comment by tleunen** [comment]
Did not get a chance to test it yet. Should do that tomorrow.

**Comment by faergeek** [comment]
Just did a rebase on master.
Also I don't see any way to trigger `change` event at all.

**Comment by tleunen** [comment]
So I checked it, with react-devtools, and there one thing I don't understand... When changing the value, the `textfield` component receive an event in `componentDidUpdate` where the `prevProps` are the props with the value I entered, and `props` empty.

But it should be the opposite.

**Comment by faergeek** [comment]
If you're testing this in demos then you can just see other fields updating too as there are rerender of parent component and we have no `shouldComponentUpdate` (and we really should) for them.

I checked it, everything is alright, except we should add `shouldComponentUpdate` hook here and I think in more places across library (will make another PR for that).

**Comment by faergeek** [comment]
I just did a rebase on top of master.

**Comment by faergeek** [comment]
Can we talk about that problem in a more real time way? May be gitter or something like that?

**Comment by tleunen** [comment]
I created the gitter room so we can discuss about it :)

**Comment by tleunen** [comment]
closing this in favor of #79

**Pull request closed without merging**
