### PR TITLE
Change peerDependencies to support beta and newer

### PR DESCRIPTION
**Pull request by faergeek**
Without that PR there will be warning when you install `react@0.14.0-beta3` or `react@0.14.0-rc1`.

### CODE REVIEW

**Comment by tleunen** [comment]
Hmm.. What do we have to set to accept all 0.14 versions?

**Comment by faergeek** [comment]
I guess first [publicly announced](https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html) beta was `beta1`. I think that would be enough.

We can go from `0.14.0-alpha1` to support all releases, but I think that now even just `rc1` would be enough. AFAIK there's no breaking changes between `beta1` and `rc1`.

So I think we should set `beta1` or `rc1`.

**Comment by tleunen** [comment]
`>= 0.13 < 0.15`, will that solve the issue?

**Comment by faergeek** [comment]
I guess. Need to try it out with both versions and check if npm shows warnings about unmeet peer dependency.

**Comment by tleunen** [comment]
We also want to set React as a devDepencency to prevent issues with npm3 :)
Will make a few tests later tonight

**Comment by faergeek** [comment]
No, having react as a dependency is the first step to include two versions of react. And it's bad and not working at all.
What issues do you have with `npm@3`? I don't have any.

**Comment by faergeek** [comment]
If you mean we should have it for tests, then I think we should find some another way for that.

**Comment by tleunen** [comment]
That's why I said "**dev**Dependency" :)

**Comment by faergeek** [comment]
Hmm, looks like redux does include `react` in `devDependencies` too.
https://github.com/rackt/react-redux/blob/master/package.json#L53

**Comment by tleunen** [comment]
The reason for this is simple. NPM doesn't install peerDependency anymore, so you have to also set it as a devDependency so you can still get the project, run the tests/demos ;-)

**Comment by faergeek** [comment]
Yeah, that makes sense :+1: 
Do you have any idea on how we can get rid of deprecation warnings in `react@0.14.x` about `findDOMNode`?

**Comment by tleunen** [comment]
Removing them once 0.14 is released :) In the meantime, I'm afraid there is no solution for that.

I was also thinking of creating a `next` branch of react-mdl based on the next version of react

**Comment by faergeek** [comment]
I think creating another branch doesn't make sense because it doesn't break anything actually.

We can add some info about `0.14.x` support to readme though.

**Comment by faergeek** [comment]
Updated

**Pull request merged**
