### PR TITLE
Allow Textfield error to be of node type

### PR DESCRIPTION
**Pull request by Gregoor**
In case you want to display a link in the error message.

### CODE REVIEW

**Comment by tleunen** [comment]
`PropTypes.node` seems to be the right thing to use then to allow all sort of "rendering" elements.

**Comment by Gregoor** [comment]
Oh, I did not know this type existed. thanks, will change!

**Comment by tleunen** [comment]
From the doc
> // Anything that can be rendered: numbers, strings, elements or an array
    // (or fragment) containing these types.
    optionalNode: React.PropTypes.node,

So only `node` is enough. Also, could you please squash your commits please?

**Comment by Gregoor** [comment]
It took a while but I think I squashed it. Always grateful for a chance to work on my git skills.

**Comment by tleunen** [comment]
perfect! :) Thanks @Gregoor

**Pull request merged**
