### PR TITLE
Add no-spacing option in Grid

### PR DESCRIPTION
**Pull request by Graf009**
Add no-spacing option in Grid

### CODE REVIEW

**Comment by tleunen** [comment]
Could you please add `nospacing` inside the `propTypes` list please?

**Comment by Graf009** [comment]
done

**Comment by tleunen** [comment]
Was also thinking, shouldn't the name of the prop be `noSpacing` instead (capital S)?
otherwise, lgtm!

**Comment by Graf009** [comment]
done

**Comment by tleunen** [comment]
LGTM.
No idea why eslint breaks on your PR now... I'll investigate this.

**Comment by tleunen** [comment]
Hey @Graf009, now that we also have a docs, could you update the PR to add the property inside the doc as well?
Let me know if that's ok, otherwise I can do it while merging it :)

**Comment by Graf009** [comment]
Sori. Now I do not have the time to do it.

**Pull request merged**
